import { User, Organization, Donation, LeaderboardEntry, Certificate } from "@/types";

export const mockUser: User = {
  id: "user-1",
  name: "Rahul Sharma",
  email: "rahul@example.com",
  phone: "+91 98765 43210",
  location: "Pune, India",
  points: 2450,
  badge: "gold",
  avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
  createdAt: "2024-01-15",
};

export const mockOrganizations: Organization[] = [
  {
    id: "org-1",
    name: "Hope Foundation",
    email: "contact@hopefoundation.org",
    phone: "+91 20 2612 3456",
    description: "Empowering underprivileged children through education and healthcare.",
    mission: "To create a world where every child has access to quality education and healthcare, regardless of their economic background.",
    category: "education",
    location: "Pune, India",
    address: "123, MG Road, Koregaon Park, Pune - 411001",
    registrationNumber: "NGO/MH/2010/12345",
    logoUrl: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=100&h=100&fit=crop",
    bannerUrl: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1200&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1497486751825-1233686d5d80?w=600&h=400&fit=crop",
      "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600&h=400&fit=crop",
    ],
    donationNeeds: [
      { id: "need-1", title: "School Supplies", description: "Notebooks, pens, and pencils for students", category: "books", urgency: "high" },
      { id: "need-2", title: "Educational Books", description: "Textbooks and reference materials", category: "books", urgency: "medium" },
    ],
    totalDonations: 1250,
    createdAt: "2020-03-15",
  },
  {
    id: "org-2",
    name: "Green Earth Initiative",
    email: "hello@greenearth.org",
    phone: "+91 20 2545 6789",
    description: "Protecting our environment through sustainable practices and awareness.",
    mission: "To preserve and restore natural ecosystems while promoting sustainable living practices in urban communities.",
    category: "environment",
    location: "Pune, India",
    address: "45, Senapati Bapat Road, Shivajinagar, Pune - 411016",
    registrationNumber: "NGO/MH/2015/67890",
    logoUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=100&h=100&fit=crop",
    bannerUrl: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=1200&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&h=400&fit=crop",
    ],
    donationNeeds: [
      { id: "need-3", title: "Saplings", description: "Native tree saplings for plantation drives", category: "other", urgency: "high" },
      { id: "need-4", title: "Gardening Tools", description: "Shovels, rakes, and watering cans", category: "other", urgency: "low" },
    ],
    totalDonations: 890,
    createdAt: "2018-06-20",
  },
  {
    id: "org-3",
    name: "Paws & Claws Shelter",
    email: "care@pawsclaws.org",
    phone: "+91 20 2678 9012",
    description: "Rescuing and rehabilitating stray animals across Maharashtra.",
    mission: "To provide shelter, medical care, and loving homes for abandoned and stray animals.",
    category: "animal-welfare",
    location: "Pune, India",
    address: "78, Kothrud, Pune - 411038",
    registrationNumber: "NGO/MH/2012/34567",
    logoUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=100&h=100&fit=crop",
    bannerUrl: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=1200&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop",
    ],
    donationNeeds: [
      { id: "need-5", title: "Pet Food", description: "Dog and cat food for shelter animals", category: "food", urgency: "high" },
      { id: "need-6", title: "Medical Supplies", description: "Vaccines and medications", category: "medical", urgency: "medium" },
    ],
    totalDonations: 567,
    createdAt: "2019-01-10",
  },
  {
    id: "org-4",
    name: "Senior Care Center",
    email: "support@seniorcare.org",
    phone: "+91 20 2789 0123",
    description: "Providing compassionate care for elderly citizens in need.",
    mission: "To ensure dignity and quality of life for senior citizens through comprehensive care services.",
    category: "elderly-care",
    location: "Pune, India",
    address: "90, Aundh, Pune - 411007",
    registrationNumber: "NGO/MH/2011/45678",
    logoUrl: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=100&h=100&fit=crop",
    bannerUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=400&fit=crop",
    images: [],
    donationNeeds: [
      { id: "need-7", title: "Medicines", description: "Common medicines for elderly patients", category: "medical", urgency: "high" },
      { id: "need-8", title: "Blankets", description: "Warm blankets for winter", category: "clothing", urgency: "medium" },
    ],
    totalDonations: 423,
    createdAt: "2017-09-05",
  },
];

export const mockDonations: Donation[] = [
  {
    id: "donation-1",
    donorId: "user-1",
    donorName: "Rahul Sharma",
    organizationId: "org-1",
    organizationName: "Hope Foundation",
    type: "books",
    quantity: "50 textbooks",
    deliveryMethod: "dropoff",
    preferredDate: "2024-11-20",
    preferredTime: "10:00 AM",
    notes: "Science and math textbooks for class 8-10",
    status: "completed",
    rewardPoints: 150,
    certificateUrl: "#certificate-1",
    createdAt: "2024-11-15",
    updatedAt: "2024-11-20",
  },
  {
    id: "donation-2",
    donorId: "user-1",
    donorName: "Rahul Sharma",
    organizationId: "org-2",
    organizationName: "Green Earth Initiative",
    type: "other",
    quantity: "20 saplings",
    deliveryMethod: "pickup",
    preferredDate: "2024-11-25",
    preferredTime: "2:00 PM",
    notes: "Mango and neem saplings",
    status: "pending",
    createdAt: "2024-11-22",
    updatedAt: "2024-11-22",
  },
  {
    id: "donation-3",
    donorId: "user-2",
    donorName: "Priya Patel",
    organizationId: "org-1",
    organizationName: "Hope Foundation",
    type: "clothing",
    quantity: "30 school uniforms",
    deliveryMethod: "dropoff",
    preferredDate: "2024-11-28",
    preferredTime: "11:00 AM",
    notes: "New uniforms in various sizes",
    status: "accepted",
    createdAt: "2024-11-24",
    updatedAt: "2024-11-25",
  },
  {
    id: "donation-4",
    donorId: "user-3",
    donorName: "Amit Kumar",
    organizationId: "org-3",
    organizationName: "Paws & Claws Shelter",
    type: "food",
    quantity: "25kg pet food",
    deliveryMethod: "pickup",
    preferredDate: "2024-11-30",
    preferredTime: "3:00 PM",
    notes: "Premium dog food",
    status: "pending",
    createdAt: "2024-11-26",
    updatedAt: "2024-11-26",
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  { rank: 1, userId: "user-5", name: "Ananya Deshmukh", location: "Pune, India", points: 5200, badge: "platinum" },
  { rank: 2, userId: "user-6", name: "Vikram Singh", location: "Mumbai, India", points: 4800, badge: "platinum" },
  { rank: 3, userId: "user-7", name: "Meera Joshi", location: "Pune, India", points: 3900, badge: "gold" },
  { rank: 4, userId: "user-1", name: "Rahul Sharma", location: "Pune, India", points: 2450, badge: "gold" },
  { rank: 5, userId: "user-8", name: "Arjun Nair", location: "Bangalore, India", points: 2100, badge: "gold" },
  { rank: 6, userId: "user-9", name: "Sneha Rao", location: "Pune, India", points: 1850, badge: "silver" },
  { rank: 7, userId: "user-10", name: "Karan Malhotra", location: "Delhi, India", points: 1600, badge: "silver" },
  { rank: 8, userId: "user-11", name: "Pooja Iyer", location: "Chennai, India", points: 1400, badge: "silver" },
  { rank: 9, userId: "user-12", name: "Rohan Gupta", location: "Pune, India", points: 980, badge: "bronze" },
  { rank: 10, userId: "user-13", name: "Nisha Sharma", location: "Hyderabad, India", points: 750, badge: "bronze" },
];

export const mockCertificates: Certificate[] = [
  {
    id: "cert-1",
    donationId: "donation-1",
    userId: "user-1",
    organizationName: "Hope Foundation",
    donationType: "books",
    date: "2024-11-20",
    downloadUrl: "#",
  },
];

export const mockOrgAuth = {
  id: "org-1",
  ...mockOrganizations[0],
};
